config/routes.rb
SourdoughApp::Application.routes.draw do
  devise_for :users, controllers: {registrations: 'users', sessions: "sessions"}
  devise_scope :user do
    authenticated do
      root to: 'users#show'
    end

    resources :users, only: [:index, :show, :edit] do
      collection do
        post :search
      end
    end
  end

  root to: 'welcome#index'
  get '/about/', to: 'welcome#about'
  get '/faq/', to: 'welcome#faq'
  get '/contact/', to: 'welcome#contact'
  get '/forum/', to: 'welcome#forum'

  resources :messages, only: [:create, :destroy]
  get   'conversation/:id',   :to => "messages#conversation",  :as => "conversation"
  get   'inbox',              :to => "messages#inbox"

  resources :images

 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

# users have 3 roles: guest visitor (not logged in), member(logged in), admin

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role? == 'admin'
        can :manage, :all
    elsif user.id?
        can :read, :all
        can [:new, :create, :show], Image
        can [:edit, :update, :destroy], Image do |image|
          image.user == user
        end
        can [:new, :create, :show], User
        can [:edit, :update, :destroy], User do |current_user|
          current_user.id == user.id
        end
        # Messages
        can [:inbox, :create, :conversation], Message
        can :destroy, Message do |message|
          (message.sender.id == current_user.id) || (message.recipient.id == current_user.id)
        end
    else
      can :read, :all
      can [:do_search, :new_search], User
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :user_id, :image
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :sender_id, :recipient_id, :content,
  :is_read, :is_archived, :created_at

  belongs_to :sender, :class_name => 'User', :foreign_key => 'sender_id'
  belongs_to :recipient, :class_name => 'User', :foreign_key => 'recipient_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :first_name, :last_name, :avatar, :first_line_address, :second_line_address, :town_city, :postcode, :country, :description, :lat, :lon, :have_need, :role
  # attr_accessible :title, :body
  mount_uploader :avatar, ImageUploader
  geocoded_by :address, :latitude  => :lat, :longitude => :lon
  after_validation :geocode


  has_many :images

  def address
    [first_line_address, second_line_address, town_city, postcode, country].compact.join(', ')
  end

  # MESSAGES
  has_many :messages_sent, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :messages_received, :class_name => 'Message', :foreign_key => 'recipient_id'

  def all_messages
    [self.messages_sent, self.messages_received].flatten
  end

  def messages_with_user other_user_id
    sent     = self.messages_sent.where("recipient_id = ?", other_user_id)
    received = self.messages_received.where("sender_id = ?", other_user_id)

    self.set_as_read(received)

    [sent, received].flatten.sort_by(&:created_at)
  end

  def set_as_read messages
    messages.each do |message|
      message.is_read = true
      message.save
    end
  end

  def contact_list
    User.find_all_by_id [users_contacted, users_contacted_by]
  end

  def count_new_messages_with user
    self.messages_received.where(sender_id: user.id, is_read: false).count
  end

  def users_contacted
    self.messages_sent.pluck(:recipient_id)   # Returns ids of users has user has sent messages to
  end

  def users_contacted_by
    self.messages_received.pluck(:sender_id)  # Returns ids of users who've messaged this user
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
    redirect_to :user
  end

  def create
    @image = Image.new(params[:image])
    @image.user = current_user
    if @image.save
      redirect_to current_user, notice: 'Image was successfully saved!'
    else
      flash.now[:alert] = 'Image was not saved!'
      redirect_to :index
    end
  end

  def show
    @image = Image.find(params[:id])
  end

  def edit

  end

  def update

  end

  def destroy

  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  authorize_resource

  def inbox
    @contact_list = current_user.contact_list
  end

  def conversation
    @other_user      = User.find params[:id]
    @message_thread  = current_user.messages_with_user params[:id]
    @new_message     = current_user.messages_sent.new(recipient_id: @other_user.id)

    render :partial => 'conversation'
  end

  def create
    message = Message.create params[:message]
    if request.xhr?
      if params[:profile]
        render nothing: true
      else
        render :partial => 'message', locals: {:message => message}
      end
    else
     redirect_to message.recipient
    end
  end

  def destroy
    Message.find(params[:id]).destroy
    if request.xhr?
      head :ok
    else
      redirect_to inbox_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def new
    @ref_user_id = params[:ref_user_id]
  end

  def create
    ref_user_id = params[:ref_user_id]
    resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")

    if is_navigational_format?
      if resource.sign_in_count == 1
        set_flash_message(:notice, :signed_in_first_time)
      else
        set_flash_message(:notice, :signed_in)
      end
    end

    sign_in(resource_name, resource)

    if ref_user_id
      redirect_to User.find(ref_user_id)
    else
      respond_with resource
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

  before_filter :authenticate_user!

  def index
    @users = User.all

    respond_to do |format|
      format.html
      format.json { render json: @users, root: false }
    end
  end

  def new
    @ref_user_id = params[:ref_user_id]
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    ref_user_id = params[:ref_user_id]

    if @user.save
      sign_in(:user, @user)

      if ref_user_id
        redirect_to User.find(ref_user_id)
      else
        redirect_to @user, notice: 'Success!'
      end
    else
      flash.now[:alert] = 'Unsuccessful sign up!'
      redirect_to '/users'
    end
  end

  def show
    @user = User.find(params[:id]) 
    @image = Image.new

    if current_user
      @message_thread  = current_user.messages_with_user @user.id
      @new_message     = current_user.messages_sent.new(recipient_id: @user.id)
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to current_user
    else
      render :edit
    end
  end

  def destroy
    redirect_to :root
  end

  def search
    @address = params[:address]

    @type = params[:type]

    @users = User.where(have_need: @type)
    
    @users_distance = {}
    @users.each do |user|
      @users_distance[user] = user.distance_to(@address)
    end

    @users_distance = @users_distance.sort_by {|k,v| v.to_s}  # sort users by distance
    @users_distance = @users_distance[0, 5]  # take only the first 5 users (the 5 closest)
    @users_distance = Hash[@users_distance]  # convert to hash

    @user_json = @users_distance.keys.map {|u| UserSerializer.new(u, root: false)}.to_json
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

  def about

  end

  def contact

  end

  def faq

  end

  def forum

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.haml
= form_for @image do |f| 
  .field
  = f.label :image
  = f.file_field :image
  .actions
  = f.submit 'Save' 

app/views/images/index.html.haml
%h2 Latest images
- @images.each do |image|
  =image_tag image.image

app/views/images/new.html.haml
%h1 Upload a new image

= render "form"

app/views/images/show.html.haml
%h2 New image
= image_tag @image.image

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sourdoughmapper
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    = stylesheet_link_tag    "application", :media => "all"
    %link{href: "http://fonts.googleapis.com/css?family=Metrophobic", rel: "stylesheet", type: "text/css"}
    %script{src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyCJPjaJXSfTPrNwZiCyvAqoVMVJ1TmIDYQ&sensor=true"}
    %script{src: "http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js", type: "text/javascript"}
    = javascript_include_tag "application"
    = csrf_meta_tags




  %body#customisation
    .container
      %nav.navbar.navbar-default{role: "navigation"}
        / overall nav

        - if user_signed_in?
          / logged in nav inc search
          .navbar-header 
            .navbar-brand
              =link_to 'Sourdoughmapper', user_path(current_user)
          .collapse.navbar-collapse
            %ul.nav.navbar-right
              %li.text-only
                %span
                  %b Hello #{current_user.username}
              %li
                %a{href: inbox_path}
                  %span.global-counter
                    = pluralize(current_user.messages_received.where(is_read: false).count, "new message")

              %li
                = link_to 'Edit Profile', edit_user_registration_path
              
              %li
                = link_to 'Sign out', destroy_user_session_path, :method => "delete"
            %form.navbar-form.navbar-left{role: "search", action:"/users/search", method: "post"}
              .form-group
                %input.form-control{placeholder: "Enter location to search for members", type: "text", name: "address"}/
              .radio
                %input#optionsRadios2{name: "type", type: "radio", value: "have", checked: true}
                %label
                  Have
                %br
                %input#optionsRadios2{name: "type", type: "radio", value: "need"}
                %label
                  Need        
              %button.btn.btn-default.nav{type: "submit"} search
        
        
        - else
          / not logged in nav inc search
          .navbar-header 
            .navbar-brand
              =link_to 'Sourdoughmapper', root_path
          .collapse.navbar-collapse
            %ul.nav.navbar-right
              %li
                - if @user
                  = link_to "Sign up" , new_user_registration_path(ref_user_id: @user.id)
                - else
                  = link_to 'Sign up', new_user_registration_path
                /|
              %li
                - if @user
                  = link_to "Sign in" , new_user_session_path(ref_user_id: @user.id)
                - else
                  = link_to 'Sign in', new_user_session_path
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}"
        
      .main= yield
    
      
      %nav.navbar.navbar-default.navbar-fixed-bottom{role: "navigation"}
        %ul.nav.navbar-left  
          %li
            = link_to 'About', about_path
          %li
            = link_to 'Contact', contact_path
          %li
            = link_to 'FAQ', faq_path
          %li
            = link_to 'Forum', forum_path
        %ul.nav.navbar-right
          %li
            %a{:href => "https://twitter.com/sourdoughmapper", :target => "_blank"}
              %img.twitter{:src => "/assets/twitter_bird_blue_32.png"}

app/views/messages/_conversation.html.haml
%h3 Messages with #{@other_user.username}
#message-thread
  - @message_thread.each do |message|
    = render message, :locals => {:message => message}

#message-compose
  = form_for @new_message do |f|
    = f.hidden_field :recipient_id
    = f.hidden_field :sender_id
    .form-group
      = f.text_area :content, {:class => 'form-control', :rows => 5}
    = f.submit 'Send', {:class => 'btn btn-primary', :id => "send-message"}

app/views/messages/inbox.html.haml
.box-css
  .row
    #inbox-contacts.col-md-3
      - if @contact_list.present?
        %h3 Contacts
        %ul.contacts-list
          - @contact_list.each do |contact|
            %li
              %a.inbox-conversation-link{href: conversation_path(contact.id)}
                #{contact.username}
                (<span class='inbox-conversation-counter'>#{current_user.count_new_messages_with(contact)}</span>)
      - else
        %h3 No messages yet

    #inbox-message-container.col-md-6

app/views/users/_form.html.haml
= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
  = devise_error_messages!
  
  %div
    = f.label :username
    %br/
    = f.text_field :username, :autofocus => true
  %div
    = f.label :first_name
    %br/
    = f.text_field :first_name
  %div
    = f.label :last_name
    %br/
    = f.text_field :last_name
  %div
    = f.label :avatar
    %br/
    = f.file_field :avatar
  %div
    = f.label :have_need, 'Select one of the following'
    %br/
    = f.select :have_need,['have', 'need']

  %div
    = f.label :first_line_address
    %br/
    = f.text_field :first_line_address
  %div
    = f.label :second_line_address
    %br/
    = f.text_field :second_line_address
  %div
    = f.label :town_city
    %br/
    = f.text_field :town_city
  %div
    = f.label :postcode
    %br/
    = f.text_field :postcode
  %div
    = f.label :country
    %br/
    = f.text_field :country
  %div
    = f.label :description
    %br/
    = f.text_field :description
  %div
    = f.label :email
    %br/
    = f.email_field :email
  %div
    = f.label :password
    %br/
    = f.password_field :password
  %div
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  %div= f.submit "Sign up"

app/views/users/_message.html.haml
.message-unit
  .message-body
    = simple_format message.content
  .message-from
    = message.sender.username
    %small #{time_ago_in_words message.created_at} ago
  = link_to 'Delete', message_path(message), {:class => 'delete-message'}

app/views/users/edit.html.haml
.box-css.col-md-4
  %h1 Edit your profile
  %form
    = form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put}) do |f|
      = devise_error_messages!
      .form-group
        = f.label :username
        = f.text_field :username, :autofocus => true, class: "form-control"
      .form-group
        = f.label :first_name
        = f.text_field :first_name, class: "form-control"
      .form-group
        = f.label :last_name
        = f.text_field :last_name, class: "form-control"
      .form-group
        = f.label :avatar
        = f.file_field :avatar, class: "form-control"
      .form-group
        = f.label :have_need, 'Do you have or need a starter?'
        = f.select :have_need,['have', 'need'], class: "form-control"
      .form-group
        = f.label :first_line_address
        = f.text_field :first_line_address, class: "form-control"
      .form-group
        = f.label :second_line_address
        = f.text_field :second_line_address, class: "form-control"
      .form-group
        = f.label :town_city
        = f.text_field :town_city, class: "form-control"
      .form-group
        = f.label :postcode
        = f.text_field :postcode, class: "form-control"
      .form-group
        = f.label :country
        = f.text_field :country, class: "form-control"
      .form-group
        = f.label :description
        = f.text_field :description, class: "form-control"
      .form-group
        = f.label :email
        = f.email_field :email, class: "form-control"
      .form-group
        = f.label :password
        = f.password_field :password, class: "form-control"
      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: "form-control"
      .form-group
        = f.submit "Save", class: "form-control"

app/views/users/index.html.haml
%h1 Latest members
- @users.each do |user|
  =link_to user.username, user
  %br
  = user.town_city
  %br
  = user.country
  %br
  = image_tag user.avatar
  %br
  = user.description

  %hr

app/views/users/new.html.haml
.box-css.col-md-4
  %h1 Sign up as a Member!
  = form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
    = devise_error_messages!
    .form-group
      = f.label :username
      = f.text_field :username, :autofocus => true, class: "form-control"
    .form-group
      = f.label :first_name
      = f.text_field :first_name, class: "form-control"
    .form-group
      = f.label :last_name
      = f.text_field :last_name, class: "form-control"
    .form-group
      = f.label :avatar
      = f.file_field :avatar, class: "form-control"
    .form-group
      = f.label :have_need, 'Select one of the following'
      = f.select :have_need,['have', 'need'], class: "form-control"
    .form-group
      = f.label :first_line_address
      = f.text_field :first_line_address, class: "form-control"
    .form-group
      = f.label :second_line_address
      = f.text_field :second_line_address, class: "form-control"
    .form-group
      = f.label :town_city
      = f.text_field :town_city, class: "form-control"
    .form-group
      = f.label :postcode
      = f.text_field :postcode, class: "form-control"
    .form-group
      = f.label :country
      = f.text_field :country, class: "form-control"
    .form-group
      = f.label :description
      = f.text_field :description, class: "form-control"
    .form-group
      = f.label :email
      = f.email_field :email, class: "form-control"
    .form-group
      = f.label :password
      = f.password_field :password, class: "form-control"
    .form-group
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: "form-control"
    - if @ref_user_id
      .form-group
        = hidden_field_tag :ref_user_id, @ref_user_id
    .form-group= f.submit "Sign up", class: "form-control"

app/views/users/search.html.haml
.box-css.col-md-12
  .row.search-result
    - if @type == 'have'
      %h2 They have a sourdough starter!
      %h3 Click on a member profile below to contact them

    - else
      %h2 They knead a sourdough starter!
      %h3 Click on a member profile below to contact them
      %br

    .col-md-3.avatar
      - @users_distance.each do |user, distance|
        = image_tag user.avatar
        %br
        = "#{distance.to_s[0, 4]} miles"
        %br
        =link_to user.username, user
        %br
        = user.town_city
        %br
        = user.country
        %br
        = user.description
        %hr

    .row
      .col-md-2
        #map-canvas-global

:javascript
  window.user_address = "#{@address}"
  window.users = #{@user_json}

app/views/users/show.html.haml
%head
  .box-css.col-md-8
    %h1 #{@user.username}'s profile
    .box.avatar
      = image_tag @user.avatar
    .box.description
      %h4 
        Location: 
        = @user.town_city
      %h4
        Country: 
        = @user.country
      %br
      %br
      = @user.description
    .box.map
      #map-canvas
    .col-md-2
    %br
      
    

    .box-css.col-md-8 
      -if @user.images.present?
        %h3 #{@user.username}'s photos
        #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
          / Indicators
          / %ol.carousel-indicators
          /   %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
          /   %li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
          /   %li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
          / Wrapper for slides
          .carousel-inner
            - @user.images.each do |image|
              .item{class: ("active" if @user.images.first.id == image.id)}
                = image_tag image.image_url(:thumb)
          / Controls
          %a.left.carousel-control{"data-slide" => "prev", href: "#carousel-example-generic"}
            %span.glyphicon.glyphicon-chevron-left
          %a.right.carousel-control{"data-slide" => "next", href: "#carousel-example-generic"}
            %span.glyphicon.glyphicon-chevron-right
    
      = form_for @image do |f| 
        .field

        -if current_user  
          %br Upload images of your triumphs (and tragedies)
          %br
          = f.file_field :image
          %br
          .actions
          = f.submit 'Save'  
  
  .box-css.col-md-4.messaging
    - if current_user
      - if current_user.id != @user.id
        %h3 Message #{@user.username}
        #message-thread
          - @message_thread.each do |message|
            = render message, :locals => {:message => message}
            
        %h4 Send a message to #{@user.username}
        #message-compose
          = form_for @new_message do |f|
            = f.hidden_field :recipient_id
            = f.hidden_field :sender_id
            .form-group
              = f.text_area :content, {:class => 'form-control', :rows => 5}
            = f.submit 'Send', {:class => 'btn btn-primary', :id => "send-message"}
    - else
      %h3 
        = link_to "Sign up" , new_user_registration_path(ref_user_id: @user.id)
        or
        = link_to "Sign in" , new_user_session_path(ref_user_id: @user.id)
        to send a message to
        = "#{@user.username}"
        
  .col-md-4.twitter
    %a.twitter-timeline{"data-widget-id" => "422083255546806272", :href => "https://twitter.com/search?q=sourdough%20OR%20sourdoughmapper", :height => "400px", "data-chrome" => "transparent nofooter noborders noheader"} Tweets about "sourdough"
  :javascript
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
 
  :javascript
  $(window).load(function() {
      $('#slider').nivoSlider();
  });

  :javascript
    window.user_location = {lat: #{@user.lat}, lon:#{@user.lon}}

app/views/welcome/about.html.haml
.box-css.col-md-8
  %h1 About
  %p
  We set up sourdoughmapper to help more people bake tasty, nutritious and cheap bread.
  %p
  The industrialised bread you can buy in supermarkets is often pretty nasty, while the 'artisanal' loaves you can buy in specialist bakeries and markets are often very expensive.
  %p
  We hope sourdoughmapper will help you:
  %ul
    %li Share, or get hold of, a sourdough starter
    %li Gain confidence in making your own bread
    %li Eat better, and more cost-effectively
    %li Make new links in your local community
  %p
  Please
  =link_to 'get in touch', contact_path
  with any queries, but most importantly, please just sign up and give it a go - you might never look back.

app/views/welcome/contact.html.haml
.box-css.col-md-8
  %h1 Contact
  
  %p
  You can contact us through the form below, or by emailing us on:
  %br
  %br
  %a{:href => "mailto:bake@sourdoughmapper.com", :target => "_top"}
    bake@sourdoughmapper.com

  %br
  %br

  %form.form-horizontal{:role => "form"}
  .form-group
    %label.col-sm-2.control-label{:for => "Name"} Name
    .col-sm-10
      %input#Name.form-control{:placeholder => "Name", :type => "name"}
  %br
  .form-group
    %label.col-sm-2.control-label{:for => "Email"} Email
    .col-sm-10
      %input#Email.form-control{:placeholder => "Email", :type => "email"}
  %br
  .form-group
    %label.col-sm-2.control-label{:for => "Message"} Message
    .col-md-4
      %textarea.form-control.message{:placeholder => "Message", :type => "message", :rows => "5"} 
  %br
  .form-group
  .col-sm-offset-2.col-sm-10
    %button.btn.btn-default{:type => "submit"} Send

app/views/welcome/faq.html.haml
.box-css.col-md-8
  %h1 Frequently Asked Questions
  %h4 What is a sourdough starter?
  %p A sourdough starter is a yeast culture that you can use to make bread, in place of commercial fast-action yeasts.
  %h4 What does one look like?
  %p Something like this:
  %img{:src => "assets/sourdough_starter.jpg"}
  %h4 Is it quite a hassle to look after?
  %p
  No. It just needs feeding with flour and water every so often.  If you bake bread a lot, it will need feeding frequently, but if you only bake bread once a week or less, you can just stick it in the fridge and forget about it until you need it again.
  %h4 But making sourdough bread is complicated, right?
  %p
  No again.  At least not once you've got the hang of it.  Check out this basic recipe.
  %h4 Do I need special equipment and ingredients?
  %p
  You need flour, water, salt, a big bowl, a baking tray and an oven.  A proving basket is optional.
  %h4 Does it take forever to make a loaf?
  %p End-to-end, yes, it takes quite a while, but for most of that time you can be doing something else (like going to work, writing a best-selling novel, going for a run, watching TV, sleeping, staring out the window...).

app/views/welcome/forum.html.haml
.box-css.col-md-8
  %h1 Forum
  The forum will go here

app/views/welcome/index.html.haml
/ - content_for :stylesheets do
:css
  / body {
  /   background: url('/assets/homeimage2.jpg');
  /   background-size: cover;
  / }  


.row
  .col-md-5.welcome-text-box
    %h1 Find, or share, some sourdough starter in your hood
    %br
    %p
      (New to sourdough bread? 
      =link_to 'Learn more...', faq_path 
      )
  .col-md-4.welcome-search-box
    %h1 I've got dough
    %h3 Share your sourdough starter and help others become successful bakers
    = form_tag search_users_path, method: :post do
      .inner-row
        = text_field_tag :address, nil, placeholder: 'Enter your location'
        = hidden_field_tag :type, 'need'
        = submit_tag :Search, class: "btn home-search-button" 
.row
  .col-md-4.welcome-search-box
    %h1 I knead dough
    %h3 Find a sourdough starter and learn how to make high quality low cost bread
    = form_tag search_users_path, method: :post do
      .inner-row
        = text_field_tag :address, nil, placeholder: 'Enter your location'
        = hidden_field_tag :type, 'have'
        = submit_tag :Search, class: "btn home-search-button"